/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.quanlytraigiam.view;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JButton;


/**
 *
 * @author PC
 */
public class MainView extends javax.swing.JFrame {
    private JButton btnPrisonerManagement;
    private JButton btnPrisonManagement;
    private JButton btnVisitManagement;
    /**
     * Creates new form MainView
     */
    public MainView() {
        
        initComponents();

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        btnChooseVisit = new javax.swing.JButton();
        btnChoosePrisoner = new javax.swing.JButton();
        btnChoosePrison = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("<html>Quản lý trại giam<br> ");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1101, 659));
        setSize(new java.awt.Dimension(960, 679));

        btnChooseVisit.setBackground(new java.awt.Color(0, 0, 102));
        btnChooseVisit.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btnChooseVisit.setForeground(new java.awt.Color(255, 255, 255));
        btnChooseVisit.setText("Quản lý thăm nuôi");
        btnChooseVisit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseVisitActionPerformed(evt);
            }
        });

        btnChoosePrisoner.setBackground(new java.awt.Color(0, 0, 102));
        btnChoosePrisoner.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btnChoosePrisoner.setForeground(new java.awt.Color(255, 255, 255));
        btnChoosePrisoner.setText("Quản lý phạm nhân");
        btnChoosePrisoner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChoosePrisonerActionPerformed(evt);
            }
        });

        btnChoosePrison.setBackground(new java.awt.Color(0, 0, 102));
        btnChoosePrison.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btnChoosePrison.setForeground(new java.awt.Color(255, 255, 255));
        btnChoosePrison.setText("Quản lý trại giam");
        btnChoosePrison.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChoosePrisonActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Quản lý trại giam thành phố X");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btnChoosePrison)
                        .addGap(21, 21, 21)
                        .addComponent(btnChoosePrisoner)
                        .addGap(18, 18, 18)
                        .addComponent(btnChooseVisit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnChooseVisit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnChoosePrisoner, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(btnChoosePrison, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(259, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChoosePrisonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChoosePrisonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChoosePrisonActionPerformed

    private void btnChoosePrisonerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChoosePrisonerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChoosePrisonerActionPerformed

    private void btnChooseVisitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseVisitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChooseVisitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }
    
    public void addChoosePrisonerListener(ActionListener listener){
        btnChoosePrisoner.addActionListener(listener);
    }
    
    public void addChoosePrisonListener(ActionListener listener){
        btnChoosePrison.addActionListener(listener);
    }
    public void addChooseVisitListener(ActionListener listener){
        btnChooseVisit.addActionListener(listener);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChoosePrison;
    private javax.swing.JButton btnChoosePrisoner;
    private javax.swing.JButton btnChooseVisit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
