/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.quanlytraigiam.view;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;

/**
 *
 * @author PC
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        btnChoosePrisoner = new javax.swing.JButton();
        btnChoosePrison = new javax.swing.JButton();
        btnChooseVisit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("<html>Quản lý trại giam<br> ");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(960, 679));

        btnChoosePrisoner.setBackground(new java.awt.Color(0, 0, 102));
        btnChoosePrisoner.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        btnChoosePrisoner.setForeground(new java.awt.Color(255, 255, 255));
        btnChoosePrisoner.setText("<html><div style='text-align: center;'>Quản lý thông tin phạm nhân<br></div>");
        btnChoosePrisoner.setToolTipText("");
        btnChoosePrisoner.setBorder(null);
        btnChoosePrisoner.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChoosePrisoner.setOpaque(true);
        btnChoosePrisoner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChoosePrisonerActionPerformed(evt);
            }
        });

        btnChoosePrison.setBackground(new java.awt.Color(0, 0, 102));
        btnChoosePrison.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        btnChoosePrison.setForeground(new java.awt.Color(255, 255, 255));
        btnChoosePrison.setText("<html><div style='text-align: center;'> Quản lý thông tin trại giam<br></div>");
        btnChoosePrison.setToolTipText("");
        btnChoosePrison.setBorder(null);
        btnChoosePrison.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChoosePrison.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnChoosePrison.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChoosePrisonActionPerformed(evt);
            }
        });

        btnChooseVisit.setBackground(new java.awt.Color(0, 0, 102));
        btnChooseVisit.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        btnChooseVisit.setForeground(new java.awt.Color(255, 255, 255));
        btnChooseVisit.setText("<html><div style='text-align: center;'>Quản lý thăm nuôi<br></div>");
        btnChooseVisit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseVisitActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("<html>Quản lý trại giam<br> ");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel9.setIcon(new ImageIcon("src/main/java/com/mycompany/quanlytraigiam/view/nentraigiam2.jpg"));
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(btnChoosePrison, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnChoosePrisoner, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnChooseVisit, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(383, 383, 383))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 1056, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 319, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnChoosePrison, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChooseVisit, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChoosePrisoner, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(205, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChoosePrisonerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChoosePrisonerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChoosePrisonerActionPerformed

    private void btnChoosePrisonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChoosePrisonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChoosePrisonActionPerformed

    private void btnChooseVisitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseVisitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChooseVisitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }
    
    public void addChoosePrisonerListener(ActionListener listener){
        btnChoosePrisoner.addActionListener(listener);
    }
    
    public void addChoosePrisonListener(ActionListener listener){
        btnChoosePrison.addActionListener(listener);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChoosePrison;
    private javax.swing.JButton btnChoosePrisoner;
    private javax.swing.JButton btnChooseVisit;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
